### ISSUE TITLE
codesandbox examples not working

### ISSUE THREAD

**Issue by cmpscabral** [formvuelate/formvuelate#266]
Sorry if this is not the best place to report this bug

**Describe the bug**
Codesandbox examples don't work

**To Reproduce**
Visit https://formvuelate.js.org/examples/

**Expected behavior**
A working example

**System Info**
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.getExperimentUserId (https://codesandbox.io/static/js/default~app~embed.03c35e4cd.chunk.js:173:1102)
    at new e (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:4078)
    at t.initializeExperimentStore (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:4954)
    at Module../src/embed/index.js (https://codesandbox.io/static/js/embed.d6aaab169.js:97:86009)
    at a (https://codesandbox.io/static/js/embed.d6aaab169.js:1:577)
    at Object.8 (https://codesandbox.io/static/js/embed.d6aaab169.js:97:86747)
    at a (https://codesandbox.io/static/js/embed.d6aaab169.js:1:577)
    at n (https://codesandbox.io/static/js/embed.d6aaab169.js:1:430)
    at https://codesandbox.io/static/js/embed.d6aaab169.js:1:6830
    at https://codesandbox.io/static/js/embed.d6aaab169.js:1:6834

**Additional context**
Using Chromium Version 92.0.4515.131 (Official Build, ungoogled-chromium) (x86_64)

**Comment by marina-mosti** [comment]
Hey @cmpscabral thanks for the report, this is a problem with codesandbox I think because it seems to be working fine for me. https://codesandbox.io/s/fvl-useschemaform-3x-w7i2f?from-embed

Codesandbox has been a little unreliable lately, I'm not entirely sure why. Maybe you could open an issue in their repo because it seems that its their code that is causing the issue. Additionally, FVL does not use localStorage for anything.
